services:
  auth-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: auth
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  product-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: product 
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - product-db-data:/var/lib/postgresql/data
    ports:
      - '5433:5432'

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672' 
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
  auth-db-data:
  product-db-data:
  rabbitmq-data:
